name: python
on:
  pull_request:
    paths:
      - ".github/**"
      - "api/**"
      - "api-contracts/**"
      - "internal/**"
      - "pkg/**"
      - "sdks/python/**"
  push:
    branches:
      - main
    paths:
      - "sdks/python/**"

defaults:
  run:
    working-directory: ./sdks/python

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.x"

      - name: Install Poetry
        run: |
          pipx install poetry==2.3.0

      - name: Run publish.sh script
        run: |
          CURRENT_PYPI_VERSION=$(pip index versions hatchet-sdk | awk 'NR==1 {gsub(/[()]/,"",$2); print $2}')
          NEW_VERSION=$(cat pyproject.toml| grep "^version =" | cut -d '"' -f 2)

          if [ "$CURRENT_PYPI_VERSION" == "$NEW_VERSION" ]; then
            echo "Version has not changed. Skipping publish."
            exit 0
          fi
          echo "VERSION_TAG=$NEW_VERSION" >> $GITHUB_ENV

      - name: "Generate release notes"
        if: env.VERSION_TAG != ''
        working-directory: ${{ github.workspace }}
        run: ./hack/ci/release-notes.sh python > ./release_notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Release"
        if: env.VERSION_TAG != ''
        working-directory: ${{ github.workspace }}
        run: |
          gh release create "py/${VERSION_TAG}" \
            --target "$GITHUB_SHA" \
            --title "Python SDK ${VERSION_TAG}" \
            --notes-file ./release_notes.md \
            --latest=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
